#########################
## Options: True or False
# Background subtraction
bgsub: True
# ilastik process
ilastik_proc: True
# Slice example dataset
slice_file: False
# Generate hexomap .tif files
generate_hexomap_files: False
# Generate hexrd .npz files
generate_hexrd_files: False
# Generate ImageD11 .flt files
generate_ImageD11_files: True
# Parallel computing or not
use_parallel_computing: False
# ImageD11 process
ImageD11_process: True

#########################

######## Standardize_format ########
sample_name: Au
# Total number of layers and detectors, and also for file name formating
layers: 1 # Number of layers, default 1 for ff-HEDM and N for nf-HEDM
dets: 1   # Detector distances for nf-HEDM, default 1 for ff-HEDM and 2 for nf-HEDM at APS sector 1
######## input_file .ge2/ge3/ge5
input_file: '/Users/yetian/Desktop/3DXRD/APS2023Feb_Au_ff.ge5'
# ff-HEDM may have empty frames to obtain data during the unstable stage of the motor
empty_images: 1
# number of frames in total including empty frames
num_images: 1441
######## input_file folder for .tif/tiff
base_dir: '/Users/yetian/Desktop/3DXRD/'
######## input_file .ge2/ge3/ge5




# omega: rotation angle for each rotation step of the motor
omega: 0.25
# Background subtraction setting: 25-25 percentile filter, 50-median fitler, 75-75 percentile, etc. Default: 50
bg_pct: 50
flip_option: 'h'  # 'v', None, 'hv'



# ilastik installed location
ilastik_loc: '/Applications/ilastik-1.4.0-OSX2.app/Contents/ilastik-release/run_ilastik.sh'
# ilastik project file which need user manually generate from ilastik GUI version
ilastik_project_file: '/Users/yetian/Desktop/Ryan_test_data/APS_2023Feb/nugget1_nf_layer0_det0_50bg.ilp'
# Parameters for convert hdf5 to hexomap .tif images
hdf5_file: '/Users/yetian/Desktop/Ryan_test_data/APS_2023Feb/nf_test/nugget1_nf_layer20_det0_50bg_proc.h5'
hdf5_file_name: 'nugget1_nf_layer20_det0_50bg_proc.h5'
input_hdf5: '/Users/yetian/Desktop/Ryan_test_data/APS_2023Feb/nf_test/'
hdf5_input_folder: '/Users/yetian/Desktop/Ryan_test_data/APS_2023Feb/nf_test/'
prefix: 'nugget1_nf_int4'
tiff_output_folder: '/Users/yetian/Desktop/Ryan_test_data/APS_2023Feb/nf_test/nf_ilastik_proc'
input_tiff_folder: '/Users/yetian/Desktop/Ryan_test_data/APS_2023Feb/nf_test/nugget1_nf_int_before'
selected_layers: [20]
start_constant: 0

#### Slice HDF5 file
slice_input_file: 'nugget1_nf_layer0_det0_50bg.h5'
input_file_path: '/imageseries/images'
slice_images: 1

#### ImageD11 input parameters
NPKS: 50
UPKS: 45
Tolseq1: 0.03
Tolseq2: 0.025
Toldist: 200
flt_THRESHOLDS: 5
Idx_prefix: 'test0'